[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[build]
  functions = "src/server"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200