export const ScientificCommitteeList = [
  { name: "Adalberto Müller", presentation: "UFF" },
  { name: "Alex Martoni", presentation: "PUC Minas" },
  { name: "Ana Cláudia Munari", presentation: "UNISC/CNPq" },
  { name: "Ana Luiza Ramazzina Ghirardi", presentation: "UNIFESP" },
  { name: "Angélica Amâncio", presentation: "Université de Poitiers" },
  {
    name: "Aurora Gedra",
    presentation: "Universidade Presbiteriana Mackenzie",
  },
  { name: "Bárbara Marques", presentation: "UEL" },
  { name: "Biagio D’Angelo", presentation: "UNB" },
  { name: "Brunilda Tempel Reichmann", presentation: "Uniandrade" },
  { name: "Camila Figueiredo", presentation: "UFMG" },
  { name: "Cássia Macieira", presentation: "UEMG" },
  { name: "Cecília Nazaré de Lima", presentation: "UFMG" },
  { name: "Clara Matheus", presentation: "UFMG" },
  {
    name: "Cristine Fickelscherer",
    presentation: "Universidade Presbiteriana Mackenzie",
  },
  { name: "Daniella Carneiro Libânio de Almada", presentation: "UFMG" },
  { name: "Eliana Lourenço de Lima Reis", presentation: "UFMG" },
  { name: "Erika Viviana Costa Vieira", presentation: "UFVJM" },
  { name: "Erick Felinto", presentation: "UERJ" },
  {
    name: "Fernando Pérez Villalón",
    presentation: "Universidad Alberto Hurtado, Chile",
  },
  { name: "Guilherme Foscolo", presentation: "UFSB" },
  { name: "Hernán Ulm", presentation: "Universidad de las Artes, Argentina" },
  { name: "Ivan Marcos Ribeiro", presentation: "UFU" },
  { name: "Kátia Hallack", presentation: "UFSJ" },
  { name: "Luciene Guimarães", presentation: "UFSJ/Capes" },
  { name: "Márcia Arbex", presentation: "UFMG/CNPq" },
  {
    name: "Maria Angélica Amâncio Santos",
    presentation: "Université de Poitiers",
  },
  { name: "Maria Cristina Cardoso Ribas", presentation: "UERJ/FAPERJ/CNPq" },
  {
    name: "Mario Cámara",
    presentation: "Universidad de Buenos Aires, Argentina",
  },
  { name: "Márcio Serelle", presentation: "PUC Minas" },
  { name: "Mateus Araújo Silva", presentation: "USP" },
  { name: "Miriam de Paiva Vieira", presentation: "UFSJ/CNPq" },
  { name: "Paulo Benites", presentation: "UFTPR" },
  { name: "Paulo Custódio de Oliveira", presentation: "UFGD" },
  {
    name: "Raquel Beatriz Junqueira Guimarães",
    presentation: "PUC Minas – CESPUC",
  },
  { name: "Sandra Cavalcante", presentation: "PUC Minas" },
  { name: "Solange Ribeiro de Oliveira", presentation: "UFMG" },
  { name: "Thais Flores Nogueira Diniz", presentation: "UFMG/CNPq" },
].sort((a, b) => a.name.localeCompare(b.name));
